using MediatR;
using Microsoft.EntityFrameworkCore;
using Wasnie.Application.Common.Abstractions;
using Wasnie.Application.Common.DTOs;
using Wasnie.Application.Common.Interfaces;
using Wasnie.Application.Compensation.Commands.Plans;
using Wasnie.Application.Compensation.Common;
using Wasnie.Application.Compensation.DTOs;
using Wasnie.Application.Compensation.Mappings;
using Wasnie.Domain.Audit;
using Wasnie.Domain.Authorization;
using Wasnie.Domain.Common.Results;
using Wasnie.Domain.Compensation.Quotas;
using Wasnie.Domain.Compensation.ValueObjects;

namespace Wasnie.Application.Compensation.Handlers.Plans;

/// <summary>
/// A plan and its quota(s) in one atomic write.
///
/// THREE PROPERTIES, each load-bearing:
///
/// 1. ATOMIC. Everything is built and validated in memory FIRST; the plan and every quota then go in
///    through a single <c>SaveChangesAsync</c>, which EF executes inside one transaction. There is no
///    code path that writes the plan and then fails on a quota. This is the whole reason the command
///    exists: a plan with an accelerator and no quota measures attainment against nothing and pays
///    €0 — silently, until payday. A half-written result here is not an inconvenience, it is a plan
///    that lies about being configured.
///
/// 2. DOMAIN PARITY. Not one business rule lives in this file. The plan goes through
///    <see cref="Domain.Compensation.Plans.Plan.Create"/> exactly as <see cref="CreatePlanHandler"/>
///    runs it; every quota goes through <see cref="QuotaBuilder.Build"/> — the same call
///    <see cref="Handlers.Quotas.CreateQuotaHandler"/> and the bulk handler make. A composite endpoint
///    that validated one rule less than the two forms it replaces would be a way to inject data those
///    forms refuse; one rule MORE would be a rule that exists only here, which is the same disease
///    facing the other way.
///
/// 3. THE PLAN ID IS KNOWN BEFORE THE WRITE. Ids in this system are generated by the application
///    (<see cref="IGuidGenerator"/>), not by the database, so the quotas can point at the plan while
///    both are still objects in memory. No intermediate save to "get the id back" — which is precisely
///    the intermediate save that would break property 1.
///
/// Deliberately NOT an <c>IMoneyCriticalCommand</c>: it writes configuration, not money, and the
/// single <c>SaveChangesAsync</c> already gives it atomicity. Marking it would make the audit pipeline
/// open an explicit transaction around it — harmless today, but the day this handler dispatches
/// another money-critical command EF would throw on the nested transaction. The molde stays simple.
/// </summary>
public sealed class CreatePlanWithQuotaHandler(
    IApplicationDbContext db,
    ITenantContext tenantContext,
    ICurrentUserService currentUser,
    IClock clock,
    IGuidGenerator guid,
    IAuditService auditService,
    IAuthorizationService authorizationService,
    ITierLimitChecker tierLimitChecker)
    : IRequestHandler<CreatePlanWithQuotaCommand, Result<CreatePlanWithQuotaResultDto>>
{
    public async Task<Result<CreatePlanWithQuotaResultDto>> Handle(
        CreatePlanWithQuotaCommand request, CancellationToken cancellationToken)
    {
        // Both authorities, because both entities are created. Doing it in one request is not a way to
        // need less permission than doing it in two.
        await authorizationService.RequireAsync(Permission.PlansCreate, cancellationToken);
        await authorizationService.RequireAsync(Permission.QuotasSet, cancellationToken);
        await tierLimitChecker.EnsurePlanLimitAsync(cancellationToken);

        var now = clock.UtcNowOffset;
        var actor = currentUser.UserId ?? "system";

        // The plan, in memory only. Its Id exists from this line on — that is what lets the quotas
        // below reference it without a save in between.
        var plan = Domain.Compensation.Plans.Plan.Create(
            tenantContext.TenantId,
            request.Name,
            request.Description,
            DateRange.Of(request.EffectiveStart, request.EffectiveEnd),
            request.Currency,
            actor,
            guid.NewGuid(),
            now,
            guid.NewGuid());

        // Names for the failure report ONLY — never a validation. The single quota create does not
        // check that the payee exists (it writes the quota and leaves the name blank on the response),
        // so checking it here would be a rule that exists only on this path. An id matching nobody
        // comes back with an empty name, which is the signal without being a new gate.
        var payeeIds = request.Quotas.Select(q => q.PayeeId).Distinct().ToList();
        var payeeById = await db.Payees
            .Where(p => payeeIds.Contains(p.Id))
            .Select(p => new { p.Id, p.FullName, p.EmployeeCode })
            .ToDictionaryAsync(p => p.Id, cancellationToken);

        var built = new List<Quota>(request.Quotas.Count);
        var failures = new List<PlanQuotaFailureDto>();

        for (var i = 0; i < request.Quotas.Count; i++)
        {
            var spec = request.Quotas[i];

            var result = QuotaBuilder.Build(
                plan,
                tenantContext.TenantId,
                spec.PayeeId,
                Money.OfNonNegative(spec.Amount, spec.Currency),
                DateRange.Of(spec.PeriodStart, spec.PeriodEnd),
                spec.MeasurementType,
                spec.Notes,
                actor,
                guid.NewGuid(),
                now);

            if (result.IsSuccess)
            {
                built.Add(result.Value!);
                continue;
            }

            payeeById.TryGetValue(spec.PayeeId, out var payee);
            failures.Add(new PlanQuotaFailureDto(i, spec.PayeeId, payee?.FullName ?? string.Empty, result.Error!));
        }

        // Refused BEFORE the write, so there is nothing to roll back — and critically, the PLAN was
        // never written either. Returning here with a fully-built plan object is the atomicity
        // guarantee: it only ever existed in memory.
        if (failures.Count > 0)
            return Result<CreatePlanWithQuotaResultDto>.Success(
                new CreatePlanWithQuotaResultDto(null, [], failures));

        db.CompensationPlans.Add(plan);
        db.Quotas.AddRange(built);

        // ★ THE ONE WRITE. Plan and quotas in a single SaveChanges → a single EF transaction → the
        // whole thing lands or none of it does. Splitting this into two saves would reintroduce
        // exactly the plan-without-quota state this command exists to make impossible.
        await db.SaveChangesAsync(cancellationToken);

        var planDto = CompensationMapper.ToPlanDto(plan);

        var quotaDtos = built
            .Select(q =>
            {
                payeeById.TryGetValue(q.PayeeId, out var payee);
                return new QuotaSummaryDto(
                    q.Id,
                    q.TenantId,
                    q.PayeeId,
                    payee?.FullName ?? string.Empty,
                    payee?.EmployeeCode ?? string.Empty,
                    q.PlanId,
                    plan.Name,
                    q.MeasurementType,
                    q.Amount.Amount,
                    q.Amount.Currency,
                    q.Period.Start,
                    q.Period.End,
                    q.Status.ToString(),
                    q.Notes,
                    q.CreatedAt);
            })
            .ToList();

        try
        {
            await auditService.LogAsync(new AuditEntry(
                TenantId: tenantContext.TenantId,
                Action: AuditActions.PlanCreated,
                ResourceType: ResourceTypes.Plan,
                ResourceId: plan.Id.ToString(),
                ActorUserId: actor,
                ActorEmail: currentUser.Email ?? string.Empty,
                DisplayName: plan.Name), cancellationToken);
        }
        catch { /* audit failures must not block the user operation — same as CreatePlanHandler */ }

        return Result<CreatePlanWithQuotaResultDto>.Success(
            new CreatePlanWithQuotaResultDto(planDto, quotaDtos, []));
    }
}
